---
- name: Configure Flask App
  hosts: all
  become: yes

  tasks:
    - name: Copy the Flask app directory to the EC2 instance
      copy:
        src: /home/ubuntu/application-code/
        dest: /var/www/myapp/
        mode: "0644"

    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Python and pip
      apt:
        name: 
          - python3
          - python3-pip
          - nginx
        state: present

    - name: Install Beautiful Soup and Requests
      pip:
        name: 
        - beautifulsoup4
        - flask
        - flask-cors

    - name: Create Nginx configuration file
      template:
        src: /home/ubuntu/application-code/nginx_config.j2
        dest: /etc/nginx/sites-available/myapp


    - name: Create a symbolic link to enable the site
      file:
        src: /etc/nginx/sites-available/myapp
        dest: /etc/nginx/sites-enabled/myapp
        state: link

    - name: Restart Nginx
      command: systemctl restart nginx.service

    - name: Start the Flask app in the background
      command: nohup python3 /var/www/myapp/app.py > /home/ubuntu/app.log 2>&1 &
      async: 6000
      poll: 0